# Render YAML for deploying a Python service (FastAPI)
# See https://render.com/docs/yaml-spec for more details
services:
  - type: web
    name: supabase-pdf-report
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        value: ""
      - key: SUPABASE_ANON_KEY
        value: ""
    healthCheckPath: "/health"
    disk: 512